import type { ShipmentDetail, ShipmentListItem } from './types';
import sampleShipment10444 from './sample-shipment-10444.json';

type DemoRow = [
  pro: number,
  description: string,
  status: string,
  customer: string,
  carrier: string | null,
  customerTotal: number,
  carrierTotal: number,
  mode?: string,
];

const rows: DemoRow[] = [
  [
    10443,
    'PALLETIZED LUMBER',
    'DEPARTED',
    'SEQUOIA FOREST PRODUCTS LLC',
    'NEW DEAL LOGISTICS INC',
    6300,
    4600,
  ],
  [
    10444,
    'PALLETIZED LUMBER',
    'DISPATCHED',
    'SEQUOIA FOREST PRODUCTS LLC',
    'ABBAS 1 CORP',
    6300,
    5800,
  ],
  [
    10453,
    'PALLETIZED LUMBER',
    'DISPATCHED',
    'SEQUOIA FOREST PRODUCTS LLC',
    'GOLD US TRANSPORTATION INC',
    7500,
    7200,
  ],
  [
    10458,
    'CONCRETE PARKING C',
    'OPEN',
    'CURBO CONCRETE SOLUTIONS LLC',
    null,
    3700,
    3000,
  ],
  [
    10468,
    'CONCRETE TIES',
    'OPEN',
    'RAILWORKS CORPORATION',
    null,
    1300,
    900,
    'TRUCKLOAD',
  ],
  [
    10469,
    'CONCRETE TIES',
    'OPEN',
    'RAILWORKS CORPORATION',
    null,
    1300,
    900,
    'TRUCKLOAD',
  ],
  [
    10470,
    'CONCRETE TIES',
    'OPEN',
    'RAILWORKS CORPORATION',
    null,
    1300,
    900,
    'TRUCKLOAD',
  ],
  [10474, 'LUMBER', 'OPEN', 'NEIMAN ENTERPRISES INC', null, 7808.8, 7000],
  [
    10477,
    'CHICKEN',
    'DEPARTED',
    'TIMBER LAKE FOODS INC',
    'NYG EXPRESS LLC',
    2450,
    2000,
  ],
  [10479, 'LUMBER', 'OPEN', 'NEIMAN ENTERPRISES INC', null, 7808.8, 0],
  [
    10480,
    'LUMBER',
    'DEPARTED',
    'NEIMAN ENTERPRISES INC',
    'DNC TRANSPORTATION INC',
    6610.4,
    6000,
  ],
  [
    10483,
    'PALLETS',
    'DELIVERED',
    'GREENLIGHT NETWORK',
    'JUST LOGISTICS LLC',
    0,
    450,
  ],
  [
    10484,
    'CHICKEN',
    'DEPARTED',
    'TIMBER LAKE FOODS INC',
    'SANTIAGO EXPRESS LLC',
    4700,
    3800,
  ],
  [
    10489,
    'PLASTIC LUMBER',
    'DEPARTED',
    'TANGENT TECHNOLOGIES',
    'VK INC',
    3300,
    3000,
  ],
  [10490, 'FRESH CHICKEN', 'OPEN', 'AMIGOS MEAT & POULTRY, LLC', null, 2700, 0],
  [
    10492,
    'PALLETIZED LUMBER',
    'DEPARTED',
    'SEQUOIA FOREST PRODUCTS LLC',
    'LOAD LINER LOGISTICS INC',
    7300,
    6300,
  ],
  [
    10496,
    'WOOD PELLETS',
    'COVERED',
    'NEIMAN ENTERPRISES INC',
    'JOSE D DE LA CRUZ INC',
    1792,
    2000,
  ],
  [
    10501,
    'LUMBER',
    'DISPATCHED',
    'NEIMAN ENTERPRISES INC',
    'NAR TRUCKING OF TN INC',
    6610.4,
    6000,
  ],
  [
    10508,
    'CHICKEN',
    'DELIVERED',
    'TIMBER LAKE FOODS INC',
    'BUKHARA TRANS INC',
    0,
    80,
  ],
  [
    10509,
    'PALLETS',
    'COVERED',
    'GREENLIGHT NETWORK',
    'TIMELESS CLARITY LLC',
    0,
    450,
  ],
];

export const demoShipments: ShipmentListItem[] = rows.map(
  ([
    pro,
    loadDescription,
    status,
    customer,
    carrier,
    customerTotal,
    carrierTotal,
    mode = 'BROKERAGE',
  ]) => ({
    pro,
    loadDescription,
    status,
    mode,
    customerTotal,
    carrierTotal,
    customer: { name: customer },
    carrier: carrier ? { name: carrier } : null,
  })
);

export const demoShipmentDetails: Record<number, ShipmentDetail> = {
  10444: {
    ...demoShipments.find((shipment) => shipment.pro === 10444)!,
    equipmentCode: 'V',
    equipmentDescription: 'VAN',
    customerMiles: 2032,
    truckMiles: 1989,
    weight: 44000,
    billableWeight: 44000,
    dispatcher: 'John A',
    truckNumber: '2833',
    customerReference: 'S102010',
    grossProfit: 500,
    netMargin: 0.0794,
    createdAt: '2026-07-09T17:40:00.000Z',
    updatedAt: '2026-07-18T15:30:28.155Z',
    specialInstructions:
      'STRAPS REQUIRED.\nMUST ACCEPT TRACKING AND KEEP TRACKING ON FOR THE ENTIRE TRIP.\nPOD MUST BE SUBMITTED WITHIN 24 HOURS.',
    stops: [
      {
        stopNumber: 1,
        type: 'pickup',
        name: 'SEQUOIA FOREST PRODUCTS',
        address: '200 ALDER GROVE ROAD',
        city: 'ARCATA',
        state: 'CA',
        zip: '95521',
        date: '2026-07-20T00:00:00.000-07:00',
        hours: '11AM',
      },
      {
        stopNumber: 2,
        type: 'delivery',
        name: 'FORNEY FENCE SUPPLY',
        address: '206 E US HWY 80',
        city: 'FORNEY',
        state: 'TX',
        zip: '75126',
        date: '2026-07-22T00:00:00.000-05:00',
        hours: '8:00-16:00',
      },
    ],
    drivers: [
      { name: 'Ehsanullah Azizi', phone: '8329881087' },
      { name: 'Sulieman Altahir', phone: '8066818308' },
    ],
    requirements: ['Delivery required', 'Straps / chains'],
    macroPointLoad: {
      orderStatus: 'Tracking Now',
      orderHyperlink:
        'https://MacroPoint-Lite.com/Gateway.aspx?Token=862c42fb-0214-4671-97cd-4d0bcc62b89a&Resource=OrderDetail',
      driverCell: '8329881087',
      trackStartDate: '2026-07-19',
      trackStartTime: '16:16',
      trackStartTimezone: 'PDT',
      trackingDuration: 85,
      trackingInterval: '15',
      lastUpdated: '2026-07-19T23:17:03.097Z',
    },
    rawPayload: sampleShipment10444,
  },
};
